
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.result.DeleteResult;
import com.mongodb.client.result.UpdateResult;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.bson.types.ObjectId;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *"mongodb+srv://diego:diego123@cluster0.wzahz.mongodb.net/ejemplo1?retryWrites=true&w=majority");
 * @author pc
 */
public class Aplicacion extends javax.swing.JFrame {
    MongoDatabase basedatos;//referencia a ejemplo1
    MongoCollection<Document> coleccion; //referencia a persona
    DefaultTableModel tablin = new DefaultTableModel();
    String idGlobal = "";
    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
        
        try{
            basedatos = new ConexionAtlas(
                    new MongoClientURI("mongodb+srv://diego:diego123@cluster0.wzahz.mongodb.net/Ejemplo1?retryWrites=true&w=majority")
                    
            ).getDatabase("Ejemplo1");
            
            coleccion = basedatos.getCollection("productos");
            
            tablin.addColumn("ID");
            tablin.addColumn("DESCRIPCION");
            tablin.addColumn("PRECIO");
            tablin.addColumn("EXISTENCIA");
            
            
            jTable1.setModel(tablin);
            
            
            jButton4.setEnabled(false);
            cargarDatos();
            
        }catch(Exception e){
            mensaje(e.getMessage());
        }
        
        
    }
    
    private void mensaje(String m){
            JOptionPane.showMessageDialog(null,m);
        }
    
    public void cargarDatos(){
        try{
            MongoCursor<Document>  documentos = coleccion.find().iterator();
            
            if(tablin.getRowCount() != 0){
                int total = tablin.getRowCount();
                for (int i = 1; i <= total; i++) {
                    tablin.removeRow(0);
                }
            }
            
            while(documentos.hasNext()){
                String[] renglon = new String[4];
                
                ArrayList<Object> doc = new ArrayList(documentos.next().values());
                renglon[0] = doc.get(0).toString();
                renglon[1] = doc.get(1).toString();
                renglon[2] = doc.get(2).toString();
                renglon[3] = doc.get(3).toString();
                
                
                tablin.addRow(renglon);
            }
        }catch(Exception e){
            mensaje(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("INSERTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("DESCRIPCION                         PRECIO                                EXISTENCIA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CARGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ACTUALIZAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(36, 36, 36)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Document insertar = new Document();
            
            insertar.put("descripcion",jTextField1.getText());
            insertar.put("precio",Float.parseFloat(jTextField2.getText()));
            insertar.put("existencia",Integer.parseInt(jTextField4.getText()));
            
            coleccion.insertOne(insertar);
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            
            mensaje("Se insertó correctamente el registro");
            
            cargarDatos();
            
        }catch(Exception e){
            mensaje(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!estaSeleccionada()){
            mensaje("ERROR!\nDebes SELECCIONAR una fila de la tabla");
            return;
        }
        
        int fila = jTable1.getSelectedRow();
        idGlobal = tablin.getValueAt(fila, 0).toString();
        int resp = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas BORRAR ID:"+idGlobal+"?");
        if(resp == JOptionPane.OK_OPTION){
            if(eliminar(idGlobal) == true){
                mensaje("Se ELIMINO correctaente");
                cargarDatos();
            }else{
                mensaje("NO se pudo ELIMINAR el ID:"+idGlobal);
            }
                
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!estaSeleccionada()){
            mensaje("ERROR!\nDebes seleccionar una fila de la tabla");
            return;
        }
        
        int fila = jTable1.getSelectedRow();
        idGlobal = tablin.getValueAt(fila, 0).toString();
        
        jTextField1.setText(tablin.getValueAt(fila, 1).toString());
        jTextField2.setText(tablin.getValueAt(fila, 2).toString());
        jTextField4.setText(tablin.getValueAt(fila, 3).toString());
        
        jButton1.setEnabled(false);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            if(idGlobal.isEmpty()){
                mensaje("ID VACIO");
                return;
            }
            //para actualizar se requieren 2 Document
            //1 que contiene el ID a actualizar
            //2 que contiene la DATA que se va a actualizar
            
            Document filtro = new Document("_id", new ObjectId(idGlobal));
            Document dataActualizar = new Document();
            
            dataActualizar.put("descripcion", jTextField1.getText());
            dataActualizar.put("precio", Float.parseFloat(jTextField2.getText()));
            dataActualizar.put("existencia", Integer.parseInt(jTextField4.getText()));
            
            
            UpdateResult resultado = coleccion.updateOne(filtro, new Document("$set",dataActualizar));
            if(resultado.getMatchedCount()==1){
                mensaje("SE ACTUALIZO");
                cargarDatos();
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField4.setText("");
            }else{
                mensaje("ERROR NO SE PUDO ACTUALIZAR");
            }
            
        }catch(Exception e){
            mensaje(e.getMessage());
        }
        jButton1.setEnabled(true);
        jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private boolean eliminar(String id){
        try{
            Document eliminar = new Document("_id", new ObjectId(id));
            DeleteResult resultado = coleccion.deleteOne(eliminar);
            if(resultado.getDeletedCount() == 1){
                return true;
            }else{
                return false;
            }
        
        }catch(Exception e){
            mensaje(e.getMessage());
        }
        return false;
    }
    
    private boolean estaSeleccionada(){
        if(jTable1.getSelectedRow() >= 0){
            return true;
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
